#!/bin/bash

DFDIR=`dirname $0 | xargs realpath`

# ---- Functions

link () {
  if [ -e $DFDIR/$1 ]; then
    if [ -e $HOME/$1 ] && [ ! -h $HOME/$1 ]; then
      mv $HOME/$1 $HOME/$1.bckp
      echo "$HOME/$1 already exists. Will back-up"
    fi

    mkdir -p `dirname $HOME/$1`
    ln -s -f $DFDIR/$1 $HOME/$1
  else
    echo "$DFDIR/$1 does not exist"
  fi
}

install () {
#  sudo pacman --noconfirm --needed -S $1
#
#  ec=$?
#  if [ $ec != 0 ]; then
#    yay --noconfirm --norebuild --noredownload -S $1
#  fi
   sudo apt-get install $1
}

# ---- Install dependencies

sudo pacman -Syu

install yay

install wget
install bat
install hub
install tmux
install ngrok
install jq
install xclip
install noto-fonts-emoji
install inotify-tools
install xmousepasteblock

install php
install nodejs
install docker
install docker-compose

install firefox
install google-chrome
install slack-desktop
install discord
install phpstorm

install spotify

if [ ! -f $HOME/git-prompt.sh ]; then
  echo "Installing git-prompt.sh"
  wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
fi

if [ ! -f $HOME/git-completion.bash ]; then
  echo "Install git-completion.bash"
  wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
fi

# ---- Back-up and link files

link .tmux.conf
link .bashrc
link .bash_prompt
link .bash_aliases
link .bash_functions
link .gitconfig
link .gitignore

source $DFDIR/.claude/install

# ---- Set up Term preferences

./gnome/load-term-profile

# ---- Init

source $HOME/.bashrc
